### ISSUE TITLE
Test and document File-Drop OVA

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild#41]
The process to test: https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html

OVA: link to be added.

Goal of task: to test this OVA, update the documentation https://github.com/k8-proxy/k8-rebuild/blob/main/documentation.md (add the steps to deploy it and how to use it) and confirm the process mentioned above.

**Comment by MaNe2020** [comment]
@svf97 @GINAGC 
Adding info from Nour:
OVA link : https://glasswall-sow-ova.s3-eu-west-1.amazonaws.com/vms/SOW-REST/sow-rest.ova
it's the same testing steps as sow-rest ova, except that you visit the web page on port 30080
(example: http://10.0.0.10:30080 instead of http://10.0.0.10) (edited)

@GINAGC in order to test this we need permission to create EC2 instance (which I do not have) or use existing one (someone should provide details for EC2 instance that we can use/reuse for testing).


@svf97 here are the steps I came up, based on the  https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html

**Prerequisites:**
1. Have EC2 instance (WE SHOULD SPECIFIED SIZE, not sure if minimum 1CPU, 1GB will work) up and running
2. Have OVA uploaded to S3 and have public link (ex. https://glasswall-sow-ova.s3-eu-west-1.amazonaws.com/vms/SOW-REST/sow-rest.ova)
3. ??? They mentioned having **IAM role named vmimport** (not sure if this is connected to S3 or EC2)

**Steps**
1. SSH to EC2 instance (AWS CLI should be installed - need to verify if it needs to be installed locally and if it comes by default with EC2 instances itself (this can maybe be moved to prerequisites)
2. Import an OVA (single disk - I suppose this is our case)
`aws ec2 import-image --description "My server VM" --disk-containers "file://C:\import\containers.json"`
where containers.json looks like
`[
  {
    "Description": "My Server OVA",
    "Format": "ova",
    "UserBucket": {
        "S3Bucket": "glasswall-sow-ova",
        "S3Key": "vms/SOW-REST/sow-rest.ova"
    }
}]`
3.  Launch an instance using the resulting AMI (we should shorten clarification from here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/launching-instance.html)

**Usage**
1. From a web browser, navigate to the VM IP address over HTTP and port 30080 (i.e: http://<VM IP ADDRESS>:30080) to access the UI
2. Click on login (no credentials needed)
3. Try to rebuild the file and verify it is cleaned

**Comment by svf97** [comment]
hello @MaNe2020 and @GINAGC 
I've updated the documentation with the steps required here: https://github.com/k8-proxy/k8-rebuild/pull/42
however, i do not have permissions for the import so i was not able to test this out

**Comment by GINAGC** [comment]
Closing issue for this release until we have another update.
